version = "0.6.2"
content_dir = "content"

[spine]
exclude = ["template.typ"]

[[html.assets]]
css_stylesheet = "./style.css"

[[html.assets]]
js_scripts = "./nav.js"

[[html.assets]]
js_scripts = "./tables.js"

[pdf.spine]
title = "Rookery"

[epub.spine]
title = "Rookery"

[packages.rookery]
repo = "https://github.com/freecomputinglab/rookery"
branch = "0.1.0"
